### ISSUE TITLE
Track user statistics

### ISSUE THREAD

**Issue by Sn8z** [Sn8z/RottenTomato#5]
We should track what pages and buttons our users use :D We could for example use Google Analytics but remember that our Rails version is 4.2 and have Turbolinks enabled!

**Comment by Snajtz** [comment]
Are there any know issues with rails 4.2 and turbolinks?

**Comment by Sn8z** [comment]
@Snajtz Yes! When Turbolinks in enabled we don't actually 'change' page so Google Analytics can't track it as you would normally do. There's a few tutorials out there though so it shouldn't be a big problem but we have to think about it :) Also we should create a '.env' file when we implement this so we don't show our 'secret' key ^^ Remember that this is a public repo ;D

**Comment by Sn8z** [comment]
We should really look at the Ahoy gem, I've given it a fast glance and it seems promising :) :dancer:

**Comment by Sn8z** [comment]
https://ankane.github.io/ahoy/ Here's the link aswell

**Comment by Sn8z** [comment]
Decided to implement Google Analytics for now
