### ISSUE TITLE
quote model

### ISSUE THREAD

**Issue by Brinkentosh** [Sn8z/RottenTomato#9]
tips and tricks that changes for every page refresh.

**Comment by Brinkentosh** [comment]
Do we want the tips to be on every "scroll" or just on the mainpage? Also where on the pages do we want to put it? Last question, How big do we want the tips to be?

**Comment by Sn8z** [comment]
I think it would look nice if we just have the tips on the first page that the user comes to. Something discrete and not too long, maybe like a tweet? about 140 chars?

**Comment by Snajtz** [comment]
I'm thinking we could have some discrete text under the search bar.

**Comment by Sn8z** [comment]
As time have passed I now feel like this aint a feature that we want anymore, therefor I close this issue
